# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a91fe74ac239d442db88d3dc79740b1c"
name = "Market Pulse"
application_url = "https://marketos.buzz"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = [ "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_inventory,read_orders,read_product_listings,read_products,write_inventory,write_product_listings,write_products"

[auth]
redirect_urls = [ "https://marketos.buzz/api/auth" ]
